package vista;

import javax.swing.JFrame;

/**
 *
 * @author cindy
 */
public class VistaMetodoAbierto extends javax.swing.JFrame {

    /**
     * Creates new form VistaMetodoAbierto
     */
    public VistaMetodoAbierto() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        pregunta = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        btnMetodoNewton = new javax.swing.JButton();
        btnMetodoSecante = new javax.swing.JButton();
        btnMetodoRaicesMultiples = new javax.swing.JButton();
        btnMetodoPuntoFijo = new javax.swing.JButton();
        btnInterpolacion = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(192, 197, 196));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen 200.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1150, -1));

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("MÉTODOS ABIERTOS");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1150, -1));

        pregunta.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        pregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pregunta.setText("Seleccione el tipo de métodos abiertos a realizar.");
        fondoPanel.add(pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1150, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        separador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        separador.setOpaque(true);
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 281, 350, -1));

        btnMetodoNewton.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnMetodoNewton.setText("MÉTODO de NEWTON");
        btnMetodoNewton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMetodoNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoNewtonActionPerformed(evt);
            }
        });
        fondoPanel.add(btnMetodoNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 240, 40));

        btnMetodoSecante.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnMetodoSecante.setText("MÉTODO SECANTE");
        btnMetodoSecante.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMetodoSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoSecanteActionPerformed(evt);
            }
        });
        fondoPanel.add(btnMetodoSecante, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 230, 40));

        btnMetodoRaicesMultiples.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnMetodoRaicesMultiples.setText("MÉTODO RAICES MÚLTIPLES");
        btnMetodoRaicesMultiples.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMetodoRaicesMultiples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoRaicesMultiplesActionPerformed(evt);
            }
        });
        fondoPanel.add(btnMetodoRaicesMultiples, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 270, 40));

        btnMetodoPuntoFijo.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnMetodoPuntoFijo.setText("MÉTODO PUNTO FIJO");
        btnMetodoPuntoFijo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMetodoPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoPuntoFijoActionPerformed(evt);
            }
        });
        fondoPanel.add(btnMetodoPuntoFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 270, 40));

        btnInterpolacion.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnInterpolacion.setText("INTERPOLACIÓN");
        btnInterpolacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInterpolacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterpolacionActionPerformed(evt);
            }
        });
        fondoPanel.add(btnInterpolacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 240, 40));

        btnRegresar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 620, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMetodoNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoNewtonActionPerformed
        VistaMetodoNewton  vi  = new VistaMetodoNewton();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMetodoNewtonActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaInicio vi = new VistaInicio();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMetodoSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoSecanteActionPerformed
        VistaMetodoSecante  vi  = new VistaMetodoSecante();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMetodoSecanteActionPerformed

    private void btnInterpolacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterpolacionActionPerformed
        VistaInterpolacion  vi  = new VistaInterpolacion();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInterpolacionActionPerformed

    private void btnMetodoPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoPuntoFijoActionPerformed
        VistaMetodoPuntoFijo  vi  = new VistaMetodoPuntoFijo();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMetodoPuntoFijoActionPerformed

    private void btnMetodoRaicesMultiplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoRaicesMultiplesActionPerformed
        VistaMetodoRaicesMultiples  vi  = new VistaMetodoRaicesMultiples();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMetodoRaicesMultiplesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoAbierto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoAbierto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoAbierto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoAbierto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMetodoAbierto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInterpolacion;
    private javax.swing.JButton btnMetodoNewton;
    private javax.swing.JButton btnMetodoPuntoFijo;
    private javax.swing.JButton btnMetodoRaicesMultiples;
    private javax.swing.JButton btnMetodoSecante;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel pregunta;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
