package vista;

import controladores.ControladorBiseccion;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import proyectometodosnumericos.metodoBiseccion;

/**
 *
 * @author cindy
 */
public class VistaMetodoBiseccion extends javax.swing.JFrame {

    private ControladorBiseccion controlador;

    /**
     * Creates new form VistaMetodoBiseccion
     */
    public VistaMetodoBiseccion() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        controlador = new ControladorBiseccion(this);
    }

    // Método para obtener los valores de la interfaz gráfica
    public JTextField getTxtFuncion() {
        return txtFuncion;
    }

    public JTextField getTxtIntervaloA() {
        return txtIntervaloA;
    }

    public JTextField getTxtIntervaloB() {
        return txtIntervaloB;
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    public JTable getTblBiseccion() {
        return tblBiseccion;
    }

    public JTable getJTable() {
        return jTable;
    }

    // Método para generar una tabla de valores de Y
    public void generarTabla(String funcion, double inicio, double fin, double paso) {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setRowCount(0); // Limpiar la tabla

        for (double x = inicio; x <= fin; x += paso) {
            double y = metodoBiseccion.evaluarFuncion(funcion, x);
            model.addRow(new Object[]{String.format("%.4f", x), String.format("%.4f", y)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        tblTablaBiseccion = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        funcion = new javax.swing.JLabel();
        intervaloA = new javax.swing.JLabel();
        intervaloB = new javax.swing.JLabel();
        txtIntervaloA = new javax.swing.JTextField();
        txtIntervaloB = new javax.swing.JTextField();
        btnResolver = new javax.swing.JButton();
        recurrencia = new javax.swing.JLabel();
        txtRecurrencia = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        txtFuncion = new javax.swing.JTextField();
        tblTablaBiseccion1 = new javax.swing.JScrollPane();
        tblBiseccion = new javax.swing.JTable();
        buscarIntervalo = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(157, 174, 202));
        fondoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoPanel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        fondoPanel.setPreferredSize(new java.awt.Dimension(1150, 670));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen 90.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1150, 100));

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("MÉTODO BISECCIÓN");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 100, 1150, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        separador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        separador.setOpaque(true);
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 127, 310, -1));

        jTable.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "X", "Y"
            }
        ));
        tblTablaBiseccion.setViewportView(jTable);

        fondoPanel.add(tblTablaBiseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 140, 340));

        funcion.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        funcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        funcion.setText("FUNCIÓN:");
        fondoPanel.add(funcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 100, 20));

        intervaloA.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        intervaloA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        intervaloA.setText("INTERVALO A:");
        fondoPanel.add(intervaloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, 20));

        intervaloB.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        intervaloB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        intervaloB.setText("INTERVALO B:");
        fondoPanel.add(intervaloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 100, 30));

        txtIntervaloA.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtIntervaloA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoPanel.add(txtIntervaloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 150, -1));

        txtIntervaloB.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtIntervaloB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoPanel.add(txtIntervaloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 150, -1));

        btnResolver.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnResolver.setText("RESOLVER");
        btnResolver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });
        fondoPanel.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 90, 30));

        recurrencia.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        recurrencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        recurrencia.setText("RECURRENCIA:");
        recurrencia.setAutoscrolls(true);
        fondoPanel.add(recurrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 180, -1));

        txtRecurrencia.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtRecurrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecurrenciaActionPerformed(evt);
            }
        });
        fondoPanel.add(txtRecurrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 140, -1));

        btnRegresar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 90, 30));

        btnInicio.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        fondoPanel.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 240, 90, 30));

        txtFuncion.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        fondoPanel.add(txtFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 260, -1));

        tblBiseccion.setBackground(new java.awt.Color(192, 197, 196));
        tblBiseccion.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        tblBiseccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "i", "a", "b", "f(a)", "f(b)", "Xr", "f(Xr)", "Tolerancia"
            }
        ));
        tblTablaBiseccion1.setViewportView(tblBiseccion);

        fondoPanel.add(tblTablaBiseccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 860, 340));

        buscarIntervalo.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buscarIntervalo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buscarIntervalo.setText("BUSCANDO INTERVALO X :");
        fondoPanel.add(buscarIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, 20));

        txtBuscar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        fondoPanel.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 140, -1));

        btnBuscar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaMetodoCerrado vi = new VistaMetodoCerrado();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VistaInicio vi = new VistaInicio();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
        controlador.resolverBiseccion();
    }//GEN-LAST:event_btnResolverActionPerformed

    private void txtRecurrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecurrenciaActionPerformed

    }//GEN-LAST:event_txtRecurrenciaActionPerformed
    public JTextField getTxtRecurrencia() {
        return txtRecurrencia;
    }
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // Obtener el rango de X ingresado en el campo "BUSCANDO INTERVALO X"
            String rango = txtBuscar.getText().trim();
            String[] partes = rango.split(","); // Dividir el rango en inicio y fin

            if (partes.length != 2) {
                JOptionPane.showMessageDialog(this, "Error: Ingresa el rango en el formato 'inicio,fin' (por ejemplo, -10,10).");
                return;
            }

            double inicio = Double.parseDouble(partes[0].trim().replace(",", ".")); // Reemplazar coma por punto
            double fin = Double.parseDouble(partes[1].trim().replace(",", ".")); // Reemplazar coma por punto

            if (inicio >= fin) {
                JOptionPane.showMessageDialog(this, "Error: El valor inicial debe ser menor que el valor final.");
                return;
            }

            // Obtener la función ingresada
            String funcion = txtFuncion.getText().trim();

            // Obtener el modelo de la tabla X.Y
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            model.setRowCount(0); // Limpiar la tabla

            // Generar los valores de X y Y en el rango especificado
            double paso = 1; // Paso para generar los valores de X
            for (double x = inicio; x <= fin; x += paso) {
                double y = metodoBiseccion.evaluarFuncion(funcion, x);
                model.addRow(new Object[]{String.format("%.2f", x), String.format("%.2f", y)});
            }

            JOptionPane.showMessageDialog(this, "Tabla generada para X en el rango [" + inicio + ", " + fin + "].");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Formato de número inválido. Usa punto (.) como separador decimal.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoBiseccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoBiseccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoBiseccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoBiseccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMetodoBiseccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnResolver;
    private javax.swing.JLabel buscarIntervalo;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel funcion;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel intervaloA;
    private javax.swing.JLabel intervaloB;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel recurrencia;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tblBiseccion;
    private javax.swing.JScrollPane tblTablaBiseccion;
    private javax.swing.JScrollPane tblTablaBiseccion1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtIntervaloA;
    private javax.swing.JTextField txtIntervaloB;
    private javax.swing.JTextField txtRecurrencia;
    // End of variables declaration//GEN-END:variables
}
