/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cindy
 */
public class VistaInterpolacionLagrange extends javax.swing.JFrame {

    /**
     * Creates new form VistaInterpolacionLagrange
     */
    public VistaInterpolacionLagrange() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        fX = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        txtX = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnResolver = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JTextField();
        txtY1 = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        txtY2 = new javax.swing.JTextField();
        txtX3 = new javax.swing.JTextField();
        txtY3 = new javax.swing.JTextField();
        txtX4 = new javax.swing.JTextField();
        txtY4 = new javax.swing.JTextField();
        txtX5 = new javax.swing.JTextField();
        txtY5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(157, 174, 202));
        fondoPanel.setMinimumSize(new java.awt.Dimension(1150, 686));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen 90.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1150, -1));

        titulo.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("MÉTODO INTERPOLACIÓN LINEAL de LAGRANGE");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1150, -1));

        fX.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fX.setText("f(x):");
        fondoPanel.add(fX, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 405, 30, -1));

        x.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        x.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        x.setText("VALOR DE X:");
        fondoPanel.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 110, -1));

        texto.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("Escriba los valores de la \"X\" y \"Y\" utilizando \",\"");
        fondoPanel.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1150, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        separador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        separador.setOpaque(true);
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 157, 690, -1));

        txtX.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtX, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 160, -1));

        txtResultado.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 405, 180, -1));

        btnRegresar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 80, 30));

        btnInicio.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        fondoPanel.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 80, 30));

        btnResolver.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnResolver.setText("RESOLVER");
        btnResolver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnResolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });
        fondoPanel.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 80, 30));

        btnLimpiar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 80, 30));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel1.setText("X");
        fondoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel2.setText("Y");
        fondoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        txtX1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 60, -1));

        txtY1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 60, -1));

        txtX2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 60, -1));

        txtY2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 60, -1));

        txtX3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 60, -1));

        txtY3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtY3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 60, -1));

        txtX4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 60, -1));

        txtY4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtY4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 60, -1));

        txtX5.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtX5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 60, -1));

        txtY5.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtY5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed

        try {
            double x = Double.parseDouble(txtX.getText());

            // Leer valores ingresados en X
            JTextField[] xFields = {txtX1, txtX2, txtX3, txtX4, txtX5};
            JTextField[] fxFields = {txtY1, txtY2, txtY3, txtY4, txtY5};

            List<Double> X = new ArrayList<>();
            List<Double> fX = new ArrayList<>();

            for (int i = 0; i < 5; i++) {
                String xText = xFields[i].getText().trim();
                String fxText = fxFields[i].getText().trim();

                if (!xText.isEmpty() && !fxText.isEmpty()) {
                    X.add(Double.parseDouble(xText));
                    fX.add(Double.parseDouble(fxText));
                }
            }

            if (X.size() < 2) {
                JOptionPane.showMessageDialog(this, "Debes ingresar al menos 2 valores en X y f(X).");
                return;
            }

            double resultado = 0;
            boolean encontrado = false;

            if (X.size() == 2) {
                // Solo 2 puntos: usar fórmula simétrica
                double X0 = X.get(0);
                double X1 = X.get(1);
                double fX0 = fX.get(0);
                double fX1 = fX.get(1);

                if (X0 == X1) {
                    JOptionPane.showMessageDialog(this, "X0 y X1 no pueden ser iguales.");
                    return;
                }

                resultado = ((x - X1) / (X0 - X1)) * fX0 + ((x - X0) / (X1 - X0)) * fX1;
                encontrado = true;

            } else {
                // Más de 2 puntos: interpolación por tramos
                for (int i = 0; i < X.size() - 1; i++) {
                    double Xi = X.get(i);
                    double Xi1 = X.get(i + 1);
                    double fXi = fX.get(i);
                    double fXi1 = fX.get(i + 1);

                    if ((x >= Xi && x <= Xi1) || (x >= Xi1 && x <= Xi)) {
                        if (Xi == Xi1) {
                            JOptionPane.showMessageDialog(this, "X[" + i + "] y X[" + (i + 1) + "] no pueden ser iguales.");
                            return;
                        }

                        resultado = ((x - Xi1) / (Xi - Xi1)) * fXi + ((x - Xi) / (Xi1 - Xi)) * fXi1;
                        encontrado = true;
                        break;
                    }
                }
            }

            if (encontrado) {
                txtResultado.setText(String.format("%.2f", resultado)); 
            } else {
                JOptionPane.showMessageDialog(this, "x está fuera del rango de los valores ingresados.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar todos los valores respectivos.");
        }
    }//GEN-LAST:event_btnResolverActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaInterpolacion vi = new VistaInterpolacion();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VistaInicio vi = new VistaInicio();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtX1.setText("");
        txtX2.setText("");
        txtX3.setText("");
        txtX4.setText("");
        txtX5.setText("");

        txtY1.setText("");
        txtY2.setText("");
        txtY3.setText("");
        txtY4.setText("");
        txtY5.setText("");

        txtX.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInterpolacionLagrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInterpolacionLagrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInterpolacionLagrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInterpolacionLagrange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInterpolacionLagrange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnResolver;
    private javax.swing.JLabel fX;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel titulo;
    public javax.swing.JTextField txtResultado;
    public javax.swing.JTextField txtX;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtX3;
    private javax.swing.JTextField txtX4;
    private javax.swing.JTextField txtX5;
    private javax.swing.JTextField txtY1;
    private javax.swing.JTextField txtY2;
    private javax.swing.JTextField txtY3;
    private javax.swing.JTextField txtY4;
    private javax.swing.JTextField txtY5;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
