package vista;

import javax.swing.JFrame;

/**
 *
 * @author cindy
 */
public class VistaMetodoBiseccion extends javax.swing.JFrame {

    /**
     * Creates new form VistaMetodoBiseccion
     */
    public VistaMetodoBiseccion() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        tblTablaBiseccion = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        funcion = new javax.swing.JLabel();
        intervaloA = new javax.swing.JLabel();
        intervaloB = new javax.swing.JLabel();
        txtIntervaloA = new javax.swing.JTextField();
        txtIntervaloB = new javax.swing.JTextField();
        btnResolver = new javax.swing.JButton();
        recurrencia = new javax.swing.JLabel();
        txtRecurrencia = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnCoeficiente1 = new javax.swing.JTextField();
        btnVariable1 = new javax.swing.JTextField();
        btnExponente1 = new javax.swing.JTextField();
        btnCoeficiente2 = new javax.swing.JTextField();
        btnVariable2 = new javax.swing.JTextField();
        btnExponente2 = new javax.swing.JTextField();
        btnCoeficiente3 = new javax.swing.JTextField();
        btnVariable3 = new javax.swing.JTextField();
        btnExponente3 = new javax.swing.JTextField();
        btnCoeficiente4 = new javax.swing.JTextField();
        btnVariable4 = new javax.swing.JTextField();
        btnExponente4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1150, 686));

        fondoPanel.setBackground(new java.awt.Color(157, 174, 202));
        fondoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoPanel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen 90.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 120, 100));

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("MÉTODO BISECCIÓN");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 100, 1150, -1));

        separador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        separador.setOpaque(true);
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 127, 310, -1));

        jTable1.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "i", "a", "b", "f(a)", "f(b)", "Xr", "f(Xr)", "Tolerancia"
            }
        ));
        tblTablaBiseccion.setViewportView(jTable1);

        fondoPanel.add(tblTablaBiseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 850, 300));

        funcion.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        funcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        funcion.setText("FUNCIÓN:");
        fondoPanel.add(funcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 100, -1));

        intervaloA.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        intervaloA.setText("INTERVALO A:");
        fondoPanel.add(intervaloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, 20));

        intervaloB.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        intervaloB.setText("INTERVALO B:");
        fondoPanel.add(intervaloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 267, -1, 30));

        txtIntervaloA.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtIntervaloA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoPanel.add(txtIntervaloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 150, -1));

        txtIntervaloB.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtIntervaloB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fondoPanel.add(txtIntervaloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 150, -1));

        btnResolver.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnResolver.setText("RESOLVER");
        btnResolver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fondoPanel.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 100, 30));

        recurrencia.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        recurrencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        recurrencia.setText("RECURRENCIA:");
        recurrencia.setAutoscrolls(true);
        fondoPanel.add(recurrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        txtRecurrencia.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        fondoPanel.add(txtRecurrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 190, 30));

        btnRegresar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 90, 30));

        btnInicio.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        fondoPanel.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 90, 30));
        fondoPanel.add(btnCoeficiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 30, -1));
        fondoPanel.add(btnVariable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 30, -1));
        fondoPanel.add(btnExponente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 158, 30, -1));
        fondoPanel.add(btnCoeficiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 30, -1));
        fondoPanel.add(btnVariable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 30, -1));
        fondoPanel.add(btnExponente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 158, 30, -1));
        fondoPanel.add(btnCoeficiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 30, -1));
        fondoPanel.add(btnVariable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 30, -1));
        fondoPanel.add(btnExponente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 158, 30, -1));
        fondoPanel.add(btnCoeficiente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 30, -1));
        fondoPanel.add(btnVariable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 30, -1));
        fondoPanel.add(btnExponente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 158, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaMetodoCerrado vi = new VistaMetodoCerrado();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VistaInicio vi = new VistaInicio();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoBiseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoBiseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoBiseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMetodoBiseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMetodoBiseccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btnCoeficiente1;
    private javax.swing.JTextField btnCoeficiente2;
    private javax.swing.JTextField btnCoeficiente3;
    private javax.swing.JTextField btnCoeficiente4;
    private javax.swing.JTextField btnExponente1;
    private javax.swing.JTextField btnExponente2;
    private javax.swing.JTextField btnExponente3;
    private javax.swing.JTextField btnExponente4;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnResolver;
    private javax.swing.JTextField btnVariable1;
    private javax.swing.JTextField btnVariable2;
    private javax.swing.JTextField btnVariable3;
    private javax.swing.JTextField btnVariable4;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel funcion;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel intervaloA;
    private javax.swing.JLabel intervaloB;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel recurrencia;
    private javax.swing.JSeparator separador;
    private javax.swing.JScrollPane tblTablaBiseccion;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtIntervaloA;
    private javax.swing.JTextField txtIntervaloB;
    private javax.swing.JTextField txtRecurrencia;
    // End of variables declaration//GEN-END:variables
}
