
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cindy
 */
public class VistaTresIncognitas extends javax.swing.JFrame {

    /**
     * Creates new form VistaTresIncognitas
     */
    public VistaTresIncognitas() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /*
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        funcion = new javax.swing.JLabel();
        X = new javax.swing.JLabel();
        Y = new javax.swing.JLabel();
        Z = new javax.swing.JLabel();
        TI = new javax.swing.JLabel();
        resultadoX = new javax.swing.JLabel();
        resultadoY = new javax.swing.JLabel();
        resultadoZ = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        x1 = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        x3 = new javax.swing.JTextField();
        y1 = new javax.swing.JTextField();
        y2 = new javax.swing.JTextField();
        y3 = new javax.swing.JTextField();
        z1 = new javax.swing.JTextField();
        z2 = new javax.swing.JTextField();
        z3 = new javax.swing.JTextField();
        ti1 = new javax.swing.JTextField();
        ti2 = new javax.swing.JTextField();
        ti3 = new javax.swing.JTextField();
        txtRespuestaX = new javax.swing.JTextField();
        txtResultadoY = new javax.swing.JTextField();
        txtResultadoZ = new javax.swing.JTextField();
        btnResolver = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(157, 174, 202));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen 90.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1150, -1));

        titulo.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("ECUACIONES con 3 INCOGNITAS");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1150, -1));

        funcion.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        funcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        funcion.setText("FUNCIÓN:");
        fondoPanel.add(funcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 20));

        X.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("X");
        fondoPanel.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 70, -1));

        Y.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Y.setText("Y");
        fondoPanel.add(Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 350, 70, -1));

        Z.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Z.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Z.setText("Z");
        fondoPanel.add(Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 70, -1));

        TI.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        TI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TI.setText("TI");
        fondoPanel.add(TI, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 70, -1));

        resultadoX.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        resultadoX.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultadoX.setText("RESULTADO \"X\":");
        fondoPanel.add(resultadoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        resultadoY.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        resultadoY.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultadoY.setText("RESULTADO \"Y\":");
        resultadoY.setToolTipText("");
        fondoPanel.add(resultadoY, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        resultadoZ.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        resultadoZ.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultadoZ.setText("RESULTADO \"Z\":");
        fondoPanel.add(resultadoZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jSeparator1.setOpaque(true);
        fondoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 157, 450, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jSeparator2.setOpaque(true);
        fondoPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 230, 1, 110));

        x1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 70, -1));

        x2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 70, -1));

        x3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        x3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 70, -1));

        y1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 70, -1));

        y2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 70, -1));

        y3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        y3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(y3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 70, -1));

        z1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        z1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(z1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 70, -1));

        z2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        z2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z2.setToolTipText("");
        z2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2ActionPerformed(evt);
            }
        });
        fondoPanel.add(z2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 70, -1));

        z3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        z3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z3ActionPerformed(evt);
            }
        });
        fondoPanel.add(z3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 70, -1));

        ti1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        ti1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti1ActionPerformed(evt);
            }
        });
        fondoPanel.add(ti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 70, -1));

        ti2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        ti2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti2ActionPerformed(evt);
            }
        });
        fondoPanel.add(ti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 70, -1));

        ti3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        ti3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti3ActionPerformed(evt);
            }
        });
        fondoPanel.add(ti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 70, -1));

        txtRespuestaX.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtRespuestaX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtRespuestaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 110, -1));

        txtResultadoY.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtResultadoY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultadoY.setToolTipText("");
        txtResultadoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoYActionPerformed(evt);
            }
        });
        fondoPanel.add(txtResultadoY, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 110, -1));

        txtResultadoZ.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtResultadoZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultadoZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoZActionPerformed(evt);
            }
        });
        fondoPanel.add(txtResultadoZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 110, -1));

        btnResolver.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnResolver.setText("RESOLVER");
        btnResolver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });
        fondoPanel.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 80, 30));

        btnRegresar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 80, 30));

        btnInicio.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        fondoPanel.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 80, 30));

        btnLimpiar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Verificacion de todos los campos 
    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed

        //Verificar campos
        if (x1.getText().trim().isEmpty() || x2.getText().trim().isEmpty() || x3.getText().trim().isEmpty()
                || y1.getText().trim().isEmpty() || y2.getText().trim().isEmpty() || y3.getText().trim().isEmpty()
                || z1.getText().trim().isEmpty() || z2.getText().trim().isEmpty() || z3.getText().trim().isEmpty()
                || ti1.getText().trim().isEmpty() || ti2.getText().trim().isEmpty() || ti3.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Debe ingresar todos los valores respectivos.");
            return;
        }

        try {
            //Convertir texto a numeros decimales. 
            float X1 = Float.parseFloat(x1.getText());
            float X2 = Float.parseFloat(x2.getText());
            float X3 = Float.parseFloat(x3.getText());

            float Y1 = Float.parseFloat(y1.getText());
            float Y2 = Float.parseFloat(y2.getText());
            float Y3 = Float.parseFloat(y3.getText());

            float Z1 = Float.parseFloat(z1.getText());
            float Z2 = Float.parseFloat(z2.getText());
            float Z3 = Float.parseFloat(z3.getText());

            float TI1 = Float.parseFloat(ti1.getText());
            float TI2 = Float.parseFloat(ti2.getText());
            float TI3 = Float.parseFloat(ti3.getText());

            // Cálculo del determinante principal
            float detA = (X1 * Y2 * Z3) + (Y1 * Z2 * X3) + (Z1 * X2 * Y3)
                    - (Y1 * X2 * Z3) - (X1 * Z2 * Y3) - (Z1 * Y2 * X3);

            if (detA == 0) {
                txtRespuestaX.setText("Sin solución");
                txtResultadoY.setText("Sin solución");
                txtResultadoZ.setText("Sin solución");
                return;
            }

            //TI = Termino independiente
            float detAx = (TI1 * Y2 * Z3) + (Y1 * Z2 * TI3) + (Z1 * TI2 * Y3)
                    - (Y1 * TI2 * Z3) - (TI1 * Z2 * Y3) - (Z1 * Y2 * TI3);

            float detAy = (X1 * TI2 * Z3) + (TI1 * Z2 * X3) + (Z1 * X2 * TI3)
                    - (TI1 * X2 * Z3) - (X1 * Z2 * TI3) - (Z1 * TI2 * X3);

            float detAz = (X1 * Y2 * TI3) + (Y1 * TI2 * X3) + (TI1 * X2 * Y3)
                    - (Y1 * X2 * TI3) - (X1 * TI2 * Y3) - (TI1 * Y2 * X3);

            float x = detAx / detA;
            float y = detAy / detA;
            float z = detAz / detA;

            txtRespuestaX.setText(String.format("%.2f", x));
            txtResultadoY.setText(String.format("%.2f", y));
            txtResultadoZ.setText(String.format("%.2f", z));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar todos los valores respectivos.");
        }
    }//GEN-LAST:event_btnResolverActionPerformed

    private void ti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaEcuaciones vi = new VistaEcuaciones();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VistaInicio vi = new VistaInicio();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        x1.setText("");
        x2.setText("");
        x3.setText("");

        y1.setText("");
        y2.setText("");
        y3.setText("");

        z1.setText("");
        z2.setText("");
        z3.setText("");

        ti1.setText("");
        ti2.setText("");
        ti3.setText("");

        txtRespuestaX.setText("");
        txtResultadoY.setText("");
        txtResultadoZ.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void ti3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti3ActionPerformed

    private void ti2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti2ActionPerformed

    private void txtResultadoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoYActionPerformed

    private void txtResultadoZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoZActionPerformed

    private void z2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z2ActionPerformed

    private void z3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTresIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTresIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTresIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTresIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTresIncognitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TI;
    private javax.swing.JLabel X;
    private javax.swing.JLabel Y;
    private javax.swing.JLabel Z;
    private javax.swing.JButton btnInicio;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnResolver;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel funcion;
    private javax.swing.JLabel imagen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel resultadoX;
    private javax.swing.JLabel resultadoY;
    private javax.swing.JLabel resultadoZ;
    private javax.swing.JTextField ti1;
    private javax.swing.JTextField ti2;
    private javax.swing.JTextField ti3;
    private javax.swing.JLabel titulo;
    public javax.swing.JTextField txtRespuestaX;
    public javax.swing.JTextField txtResultadoY;
    public javax.swing.JTextField txtResultadoZ;
    public javax.swing.JTextField x1;
    public javax.swing.JTextField x2;
    public javax.swing.JTextField x3;
    private javax.swing.JTextField y1;
    private javax.swing.JTextField y2;
    private javax.swing.JTextField y3;
    private javax.swing.JTextField z1;
    private javax.swing.JTextField z2;
    private javax.swing.JTextField z3;
    // End of variables declaration//GEN-END:variables
}
