package vista;

import javax.swing.JFrame;

/**
 *
 * @author cindy
 */
public class VistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicio
     */
    public VistaInicio() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        pregunta = new javax.swing.JLabel();
        btnMetodoCerrado = new javax.swing.JButton();
        btnMetodoAbierto = new javax.swing.JButton();
        btnRaicesPolinomios = new javax.swing.JButton();
        btnEcuaciones = new javax.swing.JButton();
        nombrePropietario = new javax.swing.JLabel();
        nombrePropietario1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(157, 174, 202));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("MÉTODOS NUMÉRICOS");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 250, 1140, -1));

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen 200.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1140, -1));

        separador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        separador.setOpaque(true);
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 294, 530, -1));

        pregunta.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        pregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pregunta.setText("Seleccione el tipo de método que desea realizar la función.");
        fondoPanel.add(pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 340, 1150, -1));

        btnMetodoCerrado.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnMetodoCerrado.setText("MÉTODOS CERRADOS");
        btnMetodoCerrado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMetodoCerrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMetodoCerrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoCerradoActionPerformed(evt);
            }
        });
        fondoPanel.add(btnMetodoCerrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 240, 41));

        btnMetodoAbierto.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnMetodoAbierto.setText("MÉTODOS ABIERTOS");
        btnMetodoAbierto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMetodoAbierto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMetodoAbierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoAbiertoActionPerformed(evt);
            }
        });
        fondoPanel.add(btnMetodoAbierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 240, 40));

        btnRaicesPolinomios.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnRaicesPolinomios.setText("RAICES de POLINOMIOS");
        btnRaicesPolinomios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRaicesPolinomios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRaicesPolinomios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaicesPolinomiosActionPerformed(evt);
            }
        });
        fondoPanel.add(btnRaicesPolinomios, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 240, 40));

        btnEcuaciones.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnEcuaciones.setText("ECUACIONES");
        btnEcuaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEcuaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEcuaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcuacionesActionPerformed(evt);
            }
        });
        fondoPanel.add(btnEcuaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 240, 40));

        nombrePropietario.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        nombrePropietario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrePropietario.setText("Luis Aroche");
        fondoPanel.add(nombrePropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1150, -1));

        nombrePropietario1.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        nombrePropietario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrePropietario1.setText("Cindy Ruano");
        fondoPanel.add(nombrePropietario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMetodoCerradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoCerradoActionPerformed
        VistaMetodoCerrado va  = new VistaMetodoCerrado();
        va.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMetodoCerradoActionPerformed

    private void btnMetodoAbiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoAbiertoActionPerformed
        VistaMetodoAbierto va  = new VistaMetodoAbierto();
        va.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMetodoAbiertoActionPerformed

    private void btnRaicesPolinomiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaicesPolinomiosActionPerformed
        VistaRaicesPolinomios va  = new VistaRaicesPolinomios();
        va.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRaicesPolinomiosActionPerformed

    private void btnEcuacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcuacionesActionPerformed
        VistaEcuaciones va  = new VistaEcuaciones();
        va.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEcuacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEcuaciones;
    private javax.swing.JButton btnMetodoAbierto;
    private javax.swing.JButton btnMetodoCerrado;
    private javax.swing.JButton btnRaicesPolinomios;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel nombrePropietario;
    private javax.swing.JLabel nombrePropietario1;
    private javax.swing.JLabel pregunta;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
