
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JFrame;

/**
 *
 * @author cindy
 */
public class VistaTresIncognitas extends javax.swing.JFrame {

    /**
     * Creates new form VistaMetodoNewton
     */
    public VistaTresIncognitas() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

        /*
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        x3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnResolver = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        y1 = new javax.swing.JTextField();
        y2 = new javax.swing.JTextField();
        y3 = new javax.swing.JTextField();
        z1 = new javax.swing.JTextField();
        z2 = new javax.swing.JTextField();
        z3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        ti1 = new javax.swing.JTextField();
        ti2 = new javax.swing.JTextField();
        ti3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        area = new javax.swing.JScrollPane();
        areA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(157, 174, 202));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen 90.png"))); // NOI18N
        fondoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 40, 940, -1));

        jLabel2.setText("ECUACIONES con 3 INCOGNITAS");
        fondoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, 50));
        fondoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 230, 20));

        jLabel3.setText("FUNCIÓN:");
        fondoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));
        fondoPanel.add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 60, -1));
        fondoPanel.add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 60, -1));
        fondoPanel.add(x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 60, -1));

        jLabel4.setText("X");
        fondoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jLabel5.setText("Y");
        fondoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        jLabel6.setText("Z");
        fondoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        btnResolver.setText("RESOLVER");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });
        fondoPanel.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, -1));

        btnRegresar.setText("REGRESAR");
        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, -1));

        btnInicio.setText("INICIO");
        fondoPanel.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));
        fondoPanel.add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 70, -1));
        fondoPanel.add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 70, -1));
        fondoPanel.add(y3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 70, -1));
        fondoPanel.add(z1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 80, -1));
        fondoPanel.add(z2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 90, -1));
        fondoPanel.add(z3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 90, -1));
        fondoPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 20, 120));

        ti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti1ActionPerformed(evt);
            }
        });
        fondoPanel.add(ti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 70, -1));
        fondoPanel.add(ti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 80, -1));
        fondoPanel.add(ti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 80, -1));

        jLabel7.setText("0");
        fondoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 10, -1));

        areA.setColumns(20);
        areA.setRows(5);
        area.setViewportView(areA);

        fondoPanel.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 430, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed

        float X1 = Float.parseFloat(x1.getText()); //hace la cadena en un valor flotante
        float X2 = Float.parseFloat(x2.getText());
        float X3 = Float.parseFloat(x3.getText());

        float Y1 = Float.parseFloat(y1.getText());
        float Y2 = Float.parseFloat(y2.getText());
        float Y3 = Float.parseFloat(y3.getText());

        float Z1 = Float.parseFloat(z1.getText());
        float Z2 = Float.parseFloat(z2.getText());
        float Z3 = Float.parseFloat(z3.getText());

        float TI1 = Float.parseFloat(ti1.getText());
        float TI2 = Float.parseFloat(ti2.getText());
        float TI3 = Float.parseFloat(ti3.getText());

        //termino independiente = detA
        float detA = (((X1 * Y2 * Z3) + (Y1 * Z2 * X3) + (Z1 * X2 * Y3)) - ((Y1 * X2 * Z3) + (X1 * Z2 * Y3) + (Z1 * Y2 * X3)));

        float detAx = (((TI1 * Y2 * Z3) + (Y1 * Z2 * TI3) + (Z1 * TI2 * Y3)) - ((Y1 * TI2 * Z3) + (TI1 * Z2 * Y3) + (Z1 * Y2 * TI3)));
        float detAy = (((X1 * TI2 * Z3) + (TI1 * Z2 * X3) + (Z1 * X2 * TI3)) - ((TI1 * X2 * Z3) + (X1 * Z2 * TI3) + (Z1 * TI2 * X3)));
        float detAz = (((X1 * Y2 * TI3) + (Y1 * TI2 * X3) + (TI1 * X2 * Y3)) - ((Y1 * X2 * TI3) + (X1 * TI2 * Y3) + (TI1 * Y2 * X3)));

        float x = detAx / detA;
        float y = detAy / detA;
        float z = detAz / detA;

        String respuesta = "X: " + x + "\nY: " + y + "\nZ: " + z;
        areA.setText(respuesta);
    }//GEN-LAST:event_btnResolverActionPerformed

    private void ti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTresIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTresIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTresIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTresIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTresIncognitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areA;
    private javax.swing.JScrollPane area;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnResolver;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField ti1;
    private javax.swing.JTextField ti2;
    private javax.swing.JTextField ti3;
    public javax.swing.JTextField x1;
    public javax.swing.JTextField x2;
    public javax.swing.JTextField x3;
    private javax.swing.JTextField y1;
    private javax.swing.JTextField y2;
    private javax.swing.JTextField y3;
    private javax.swing.JTextField z1;
    private javax.swing.JTextField z2;
    private javax.swing.JTextField z3;
    // End of variables declaration//GEN-END:variables
}
