/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author cindy
 */
public class VistaCuatroIncognitas extends javax.swing.JFrame {

    /**
     * Creates new form VistaCuatroIncognitas
     */
    public VistaCuatroIncognitas() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    // Método para calcular determinante de matriz 4x4
    // det(m)=m00*det(M00)−m01*det(M01)+m02*det(M02)−m03*det(M03)
    // m0j = cada elemento de la 1 fila || M0j = menor complementario
    private double determinante4x4(double[][] m) {
        return m[0][0] * determinante3x3(m[1][1], m[1][2], m[1][3],
                m[2][1], m[2][2], m[2][3],
                m[3][1], m[3][2], m[3][3])
                - m[0][1] * determinante3x3(m[1][0], m[1][2], m[1][3],
                        m[2][0], m[2][2], m[2][3],
                        m[3][0], m[3][2], m[3][3])
                + m[0][2] * determinante3x3(m[1][0], m[1][1], m[1][3],
                        m[2][0], m[2][1], m[2][3],
                        m[3][0], m[3][1], m[3][3])
                - m[0][3] * determinante3x3(m[1][0], m[1][1], m[1][2],
                        m[2][0], m[2][1], m[2][2],
                        m[3][0], m[3][1], m[3][2]);
    }

    // Método para calcular determinante de matriz 3x3
    // det=a11*(a22*a33−a23*a32)−a12*(a21*a33−a23*a31)+a13*(a21*a32−a22*a31)
    private double determinante3x3(double a11, double a12, double a13,
            double a21, double a22, double a23,
            double a31, double a32, double a33) {
        return a11 * (a22 * a33 - a23 * a32)
                - a12 * (a21 * a33 - a23 * a31)
                + a13 * (a21 * a32 - a22 * a31);
    }

    // Método para reemplazar la columna 'col' de una matriz 4x4 con un vector columna de 4 elementos
    private double[][] reemplazarColumna(double[][] matriz, double[] columna, int col) {
        double[][] nueva = new double[4][4];
        for (int i = 0; i < 4; i++) {
            System.arraycopy(matriz[i], 0, nueva[i], 0, 4);
            nueva[i][col] = columna[i];
        }
        return nueva;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtX2 = new javax.swing.JTextField();
        txtX1 = new javax.swing.JTextField();
        txtX3 = new javax.swing.JTextField();
        txtX4 = new javax.swing.JTextField();
        txtY1 = new javax.swing.JTextField();
        txtZ1 = new javax.swing.JTextField();
        txtU1 = new javax.swing.JTextField();
        txtY2 = new javax.swing.JTextField();
        txtZ2 = new javax.swing.JTextField();
        txtU2 = new javax.swing.JTextField();
        txtY3 = new javax.swing.JTextField();
        txtZ3 = new javax.swing.JTextField();
        txtU3 = new javax.swing.JTextField();
        txtY4 = new javax.swing.JTextField();
        txtZ4 = new javax.swing.JTextField();
        txtU4 = new javax.swing.JTextField();
        txtTI1 = new javax.swing.JTextField();
        txtTI2 = new javax.swing.JTextField();
        txtTI3 = new javax.swing.JTextField();
        txtTI4 = new javax.swing.JTextField();
        btnResolver = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtResultadoX = new javax.swing.JTextField();
        txtResultadoY = new javax.swing.JTextField();
        txtResultadoZ = new javax.swing.JTextField();
        txtResultadoU = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(157, 174, 202));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen 90.png"))); // NOI18N
        fondoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 60, 1150, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ECUACIONES con 4 INCOGNITAS");
        fondoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1150, -1));
        fondoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("FUNCIÓN:");
        fondoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        txtX2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtX2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 70, -1));

        txtX1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtX1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 70, -1));

        txtX3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtX3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 70, -1));

        txtX4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtX4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 70, -1));

        txtY1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtY1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtY1.setToolTipText("");
        fondoPanel.add(txtY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 70, -1));

        txtZ1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtZ1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 70, -1));

        txtU1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtU1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 70, -1));

        txtY2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtY2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtY2ActionPerformed(evt);
            }
        });
        fondoPanel.add(txtY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 70, -1));

        txtZ2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtZ2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 70, -1));

        txtU2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtU2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 70, -1));

        txtY3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtY3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtY3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 70, -1));

        txtZ3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtZ3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 70, -1));

        txtU3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtU3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 70, -1));

        txtY4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtY4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtY4ActionPerformed(evt);
            }
        });
        fondoPanel.add(txtY4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 70, -1));

        txtZ4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtZ4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtZ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 70, -1));

        txtU4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtU4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtU4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 70, -1));

        txtTI1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtTI1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtTI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 70, -1));

        txtTI2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtTI2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtTI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 70, -1));

        txtTI3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtTI3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtTI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 70, -1));

        txtTI4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtTI4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtTI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 70, -1));

        btnResolver.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnResolver.setText("RESOLVER");
        btnResolver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });
        fondoPanel.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 80, 30));

        btnLimpiar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 80, 30));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("RESULTADO \"X\":");
        fondoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("RESULTADO \"Y\":");
        fondoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("RESULTADO \"Z\":");
        fondoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("RESULTADO \"U\":");
        fondoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, -1, -1));

        txtResultadoX.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtResultadoX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtResultadoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 100, -1));

        txtResultadoY.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtResultadoY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtResultadoY, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 100, -1));

        txtResultadoZ.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtResultadoZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtResultadoZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 90, -1));

        txtResultadoU.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtResultadoU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fondoPanel.add(txtResultadoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, 90, -1));

        btnRegresar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 80, 30));

        btnInicio.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        fondoPanel.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 80, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jSeparator2.setOpaque(true);
        fondoPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 1, 150));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        fondoPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 70, -1));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Y");
        fondoPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 70, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Z");
        fondoPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 70, -1));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("U");
        fondoPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 70, -1));

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TI");
        fondoPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 70, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jSeparator3.setOpaque(true);
        fondoPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 157, 450, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtX1.setText("");
        txtX2.setText("");
        txtX3.setText("");
        txtX4.setText("");

        txtY1.setText("");
        txtY2.setText("");
        txtY3.setText("");
        txtY4.setText("");

        txtZ1.setText("");
        txtZ2.setText("");
        txtZ3.setText("");
        txtZ4.setText("");

        txtU1.setText("");
        txtU2.setText("");
        txtU3.setText("");
        txtU4.setText("");

        txtTI1.setText("");
        txtTI2.setText("");
        txtTI3.setText("");
        txtTI4.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed

        try {
            // Validar que ningún campo esté vacío
            JTextField[] campos = {
                txtX2, txtY1, txtZ1, txtU1, txtTI1,
                txtX1, txtY2, txtZ2, txtU2, txtTI2,
                txtX3, txtY3, txtZ3, txtU3, txtTI3,
                txtX4, txtY4, txtZ4, txtU4, txtTI4
            };

            for (JTextField campo : campos) {
                if (campo.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar todos los valores respectivos.");
                    return;
                }
            }

            // Leer coeficientes desde JTextFields
            double[][] A = new double[4][4];
            double[] B = new double[4];

            A[0][0] = Double.parseDouble(txtX2.getText());
            A[0][1] = Double.parseDouble(txtY1.getText());
            A[0][2] = Double.parseDouble(txtZ1.getText());
            A[0][3] = Double.parseDouble(txtU1.getText());
            B[0] = Double.parseDouble(txtTI1.getText());

            A[1][0] = Double.parseDouble(txtX1.getText());
            A[1][1] = Double.parseDouble(txtY2.getText());
            A[1][2] = Double.parseDouble(txtZ2.getText());
            A[1][3] = Double.parseDouble(txtU2.getText());
            B[1] = Double.parseDouble(txtTI2.getText());

            A[2][0] = Double.parseDouble(txtX3.getText());
            A[2][1] = Double.parseDouble(txtY3.getText());
            A[2][2] = Double.parseDouble(txtZ3.getText());
            A[2][3] = Double.parseDouble(txtU3.getText());
            B[2] = Double.parseDouble(txtTI3.getText());

            A[3][0] = Double.parseDouble(txtX4.getText());
            A[3][1] = Double.parseDouble(txtY4.getText());
            A[3][2] = Double.parseDouble(txtZ4.getText());
            A[3][3] = Double.parseDouble(txtU4.getText());
            B[3] = Double.parseDouble(txtTI4.getText());

            // Determinante principal
            double detA = determinante4x4(A);
            if (detA == 0) {
                JOptionPane.showMessageDialog(this, "El sistema no tiene solución única (determinante = 0).");
                return;
            }

            // Reemplazo de columnas || Método Cramer
            double x = determinante4x4(reemplazarColumna(A, B, 0)) / detA;
            double y = determinante4x4(reemplazarColumna(A, B, 1)) / detA;
            double z = determinante4x4(reemplazarColumna(A, B, 2)) / detA;
            double u = determinante4x4(reemplazarColumna(A, B, 3)) / detA;

            // Mostrar resultados con dos decimales
            txtResultadoX.setText(String.format("%.2f", x));
            txtResultadoY.setText(String.format("%.2f", y));
            txtResultadoZ.setText(String.format("%.2f", z));
            txtResultadoU.setText(String.format("%.2f", u));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, asegúrate de ingresar valores numéricos válidos.");
        }
    }//GEN-LAST:event_btnResolverActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaEcuaciones vi = new VistaEcuaciones();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VistaInicio vi = new VistaInicio();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void txtY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtY2ActionPerformed
    }//GEN-LAST:event_txtY2ActionPerformed

    private void txtY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtY4ActionPerformed
    }//GEN-LAST:event_txtY4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCuatroIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCuatroIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCuatroIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCuatroIncognitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCuatroIncognitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnResolver;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JTextField txtResultadoU;
    public javax.swing.JTextField txtResultadoX;
    public javax.swing.JTextField txtResultadoY;
    public javax.swing.JTextField txtResultadoZ;
    private javax.swing.JTextField txtTI1;
    private javax.swing.JTextField txtTI2;
    private javax.swing.JTextField txtTI3;
    private javax.swing.JTextField txtTI4;
    private javax.swing.JTextField txtU1;
    private javax.swing.JTextField txtU2;
    private javax.swing.JTextField txtU3;
    private javax.swing.JTextField txtU4;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtX3;
    private javax.swing.JTextField txtX4;
    private javax.swing.JTextField txtY1;
    private javax.swing.JTextField txtY2;
    private javax.swing.JTextField txtY3;
    private javax.swing.JTextField txtY4;
    private javax.swing.JTextField txtZ1;
    private javax.swing.JTextField txtZ2;
    private javax.swing.JTextField txtZ3;
    private javax.swing.JTextField txtZ4;
    // End of variables declaration//GEN-END:variables
}
