/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JFrame;

/**
 *
 * @author cindy
 */
public class VistaInterpolacionNewton extends javax.swing.JFrame {

    /**
     * Creates new form VistaInterpolacionNewton
     */
    public VistaInterpolacionNewton() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        X = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        txtX = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnResolver = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanel.setBackground(new java.awt.Color(157, 174, 202));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen 90.png"))); // NOI18N
        fondoPanel.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1150, -1));

        titulo.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("MÉTODO INTERPOLACIÓN LINEAL de NEWTON");
        fondoPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1150, -1));

        X.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        X.setText("VALOR DE X:");
        fondoPanel.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 130, -1));

        texto.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("Escriba los valores de la \"X\" y \"Y\" utilizando \",\"");
        fondoPanel.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1150, -1));

        resultado.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultado.setText("y:");
        fondoPanel.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 30, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        separador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        separador.setOpaque(true);
        fondoPanel.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 157, 690, -1));

        txtX.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtX, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 120, -1));

        txtResultado.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fondoPanel.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 250, -1));

        btnResolver.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnResolver.setText("RESOLVER");
        btnResolver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fondoPanel.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 80, 30));

        btnRegresar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        fondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 80, 30));

        btnInicio.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        fondoPanel.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 80, 30));

        btnGenerar.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btnGenerar.setText("GENERAR");
        btnGenerar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fondoPanel.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 80, 30));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "X", "Y"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        fondoPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 310, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaInterpolacion vi = new VistaInterpolacion();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VistaInicio vi = new VistaInicio();
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInterpolacionNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInterpolacionNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInterpolacionNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInterpolacionNewton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInterpolacionNewton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X;
    public javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnResolver;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultado;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tblDatos;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel titulo;
    public javax.swing.JTextField txtResultado;
    public javax.swing.JTextField txtX;
    // End of variables declaration//GEN-END:variables
}
